ci: regroup e2e CIs

diff --git a/.github/workflows/e2e_tests.yml b/.github/workflows/e2e_tests.yml
--- a/.github/workflows/e2e_tests.yml
+++ b/.github/workflows/e2e_tests.yml
@@ -1,3 +1,9 @@
+# several test modes:
+# - MASTER_STAGING: master branch against staging
+# - RELEASE_PREPROD: latest release branch against preprod
+# - MASTER_LTS: master branch against LTS
+# - PREV_RELEASE_TESTS_STAGING: SDK from master, previous release tests against staging
+
 name: E2E tests
 on:
   workflow_dispatch:
@@ -11,22 +17,23 @@ on:
         required: true
         default: "true"
       testType:
-        description: "Test type"
+        description: "Test type: MASTER_STAGING (master branch against staging), RELEASE_PREPROD (latest release branch against preprod), MASTER_LTS (master branch against LTS), PREV_RELEASE_TESTS_STAGING (SDK from master, previous release tests against staging)"
         required: true
         type: choice
+        default: "MASTER_STAGING"
         options:
-          - master against staging
-          - last release branch against preprod
-          - master against LTS
-          - SDK from master, previous release tests against staging
+          - MASTER_STAGING
+          - RELEASE_PREPROD
+          - MASTER_LTS
+          - PREV_RELEASE_TESTS_STAGING
   push:
     branches:
       - "release/**"
       - master
   schedule:
-    - cron: "0 7,15 * * 1-5" # classic tests (master against staging), twice a day
-    - cron: "0 13 * * 1-5" # LTS tests (master against LTS)
-    - cron: "0 12 * * 1-5" # Kili SDK from master, previous release tests against staging
+    - cron: "0 7,15 * * 1-5" # MASTER_STAGING
+    - cron: "0 13 * * 1-5" # MASTER_LTS
+    - cron: "0 12 * * 1-5" # PREV_RELEASE_TESTS_STAGING
 
 jobs:
   tests:
@@ -36,8 +43,99 @@ jobs:
         os: [ubuntu-latest, windows-latest]
     runs-on: ${{ matrix.os }}
     steps:
+      - name: Setup test mode
+        shell: bash
+        run: |
+          if [[ "${{ github.event_name }}" == "push" ]]; then
+
+            if [[ "${{ github.ref_name }}" == release/* ]]; then
+              echo "TEST_MODE=RELEASE_PREPROD" >> $GITHUB_ENV
+            else
+              echo "TEST_MODE=MASTER_STAGING" >> $GITHUB_ENV
+            fi
+
+          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
+
+            if [[ "${{ github.event.schedule }}" == "0 7,15 * * 1-5" ]]; then
+              echo "TEST_MODE=MASTER_STAGING" >> $GITHUB_ENV
+
+            elif [[ "${{ github.event.schedule }}" == "0 13 * * 1-5" ]]; then
+              echo "TEST_MODE=MASTER_LTS" >> $GITHUB_ENV
+
+            elif [[ "${{ github.event.schedule }}" == "0 12 * * 1-5" ]]; then
+              echo "TEST_MODE=PREV_RELEASE_TESTS_STAGING" >> $GITHUB_ENV
+
+            fi
+
+          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            echo "TEST_MODE=${{ github.event.inputs.testType }}" >> $GITHUB_ENV
+
+          fi
+
+      - name: Check that test mode is valid
+        shell: bash
+        run: |
+          if [[ ${{ env.TEST_MODE }} != "MASTER_STAGING" ]] || \
+             [[ ${{ env.TEST_MODE }} != "RELEASE_PREPROD" ]] || \
+             [[ ${{ env.TEST_MODE }} != "MASTER_LTS" ]] || \
+             [[ ${{ env.TEST_MODE }} != "PREV_RELEASE_TESTS_STAGING" ]]; then
+            echo "Invalid test mode: ${{ env.TEST_MODE }}"
+            exit 1
+          fi
+
+      - name: Get latest release branch
+        shell: bash
+        run: |
+          last_version=$(curl --silent "https://api.github.com/repos/kili-technology/kili-python-sdk/releases/latest" | jq -r .tag_name)
+          echo "Last version: $last_version"
+
+          IFS=. read -r major minor patch <<< "$last_version"
+          last_minor_version="$major.$minor.0"
+          echo "LASTEST_RELEASE_BRANCH=release/$last_minor_version" >> $GITHUB_ENV
+
+      - name: Set checkout branch
+        shell: bash
+        run: |
+          if [[ "${{ env.TEST_MODE }}" == "MASTER_STAGING" ]]; then
+            echo "REF=master" >> $GITHUB_ENV
+            echo "TEST_AGAINST=STAGING" >> $GITHUB_ENV
+            echo "KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/v2/graphql" >> $GITHUB_ENV
+
+          elif [[ "${{ env.TEST_MODE }}" == "RELEASE_PREPROD" ]]; then
+            echo "REF=${{ env.LASTEST_RELEASE_BRANCH }}" >> $GITHUB_ENV
+            echo "TEST_AGAINST=PREPROD" >> $GITHUB_ENV
+            echo "KILI_API_ENDPOINT=https://preproduction.cloud.kili-technology.com/api/label/v2/graphql" >> $GITHUB_ENV
+
+          elif [[ "${{ env.TEST_MODE }}" == "MASTER_LTS" ]]; then
+            echo "REF=master" >> $GITHUB_ENV
+            echo "TEST_AGAINST=LTS" >> $GITHUB_ENV
+            echo "KILI_API_ENDPOINT=https://lts.cloud.kili-technology.com/api/label/v2/graphql" >> $GITHUB_ENV
+
+          elif [[ "${{ env.TEST_MODE }}" == "PREV_RELEASE_TESTS_STAGING" ]]; then
+            echo "REF=${{ env.LASTEST_RELEASE_BRANCH }}" >> $GITHUB_ENV
+            echo "TEST_AGAINST=STAGING" >> $GITHUB_ENV
+            echo "KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/v2/graphql" >> $GITHUB_ENV
+
+          fi
+
+      - name: Check REF is set
+        shell: bash
+        run: |
+          if [[ -z "${{ env.REF }}" ]]; then
+            echo "REF is not set"
+            exit 1
+          fi
+
       - name: Checkout repo
         uses: actions/checkout@v3
+        with:
+          ref: ${{ env.REF }}
+
+      - name: Delete src for PREV_RELEASE_TESTS_STAGING mode
+        if: env.TEST_MODE == 'PREV_RELEASE_TESTS_STAGING'
+        shell: bash
+        run: |
+          rm -rf src
 
       - name: Set up Python 3.7
         uses: actions/setup-python@v4
@@ -45,22 +143,22 @@ jobs:
           python-version: 3.7
           cache: "pip"
 
-      - name: Install dependencies
+      - name: Upgrade pip
         run: |
           python -m pip install --upgrade pip
-          pip install -e ".[dev]"
 
-      - name: Set proper test server (preprod, staging)
+      - name: Install kili
+        run: |
+          if [[ "${{ env.TEST_MODE }}" == "PREV_RELEASE_TESTS_STAGING" ]]; then
+            pip install "kili[dev] @ git+https://github.com/kili-technology/kili-python-sdk.git@master"
+          else
+            pip install -e ".[dev]"
+          fi
+
+      - name: Get kili version
         shell: bash
         run: |
-          # if branch starts with "release/", then test against preprod
-          if [[ "${{ github.ref_name }}" == release/* ]]; then
-            echo "TEST_AGAINST=PREPROD" >> $GITHUB_ENV
-            echo "KILI_API_ENDPOINT=https://preproduction.cloud.kili-technology.com/api/label/v2/graphql" >> $GITHUB_ENV
-          else
-            echo "TEST_AGAINST=STAGING" >> $GITHUB_ENV
-            echo "KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/v2/graphql" >> $GITHUB_ENV
-          fi
+          echo "KILI_SDK_VERSION=$(python -c "from kili import __version__; print(__version__)")" >> $GITHUB_ENV
 
       - name: E2E tests
         if: github.event.inputs.runE2ETests != 'false'
@@ -74,9 +172,7 @@ jobs:
           KILI_USER_ID: ${{ secrets[format('KILI_USER_ID_{0}', env.TEST_AGAINST)] }}
 
       - name: Notebook tests
-        if: >-
-          github.event.inputs.runNotebookTests != 'false' &&
-          (github.event_name != 'push' || github.ref_name != 'master')
+        if: github.event.inputs.runNotebookTests != 'false' && (github.event_name != 'push' || github.ref_name != 'master') # Do not run notebook tests after merging to master
         timeout-minutes: 15
         run: pytest -ra -sv --color yes --code-highlight yes --durations=15 -vv tests/test_notebooks.py
         env:
@@ -86,6 +182,18 @@ jobs:
           KILI_USER_EMAIL: ${{ secrets[format('KILI_USER_EMAIL_{0}', env.TEST_AGAINST)] }}
           KILI_USER_ID: ${{ secrets[format('KILI_USER_ID_{0}', env.TEST_AGAINST)] }}
 
+      - name: Check that kili has not been updated by notebooks
+        shell: bash
+        run: |
+          kili_sdk_version=$(python -c "from kili import __version__; print(__version__)")
+          if [[ "${{ env.KILI_SDK_VERSION }}" != "$kili_sdk_version" ]]; then
+            echo "Kili has been updated (maybe by notebooks)."
+            echo "The version should not be updated during tests."
+            echo "version before: ${{ env.KILI_SDK_VERSION }}"
+            echo "version after: $kili_sdk_version"
+            exit 1
+          fi
+
       - name: Slack notification if failure
         if: failure() && (github.event_name != 'workflow_dispatch') # doesn't notify for manual runs
         id: slack
@@ -93,13 +201,13 @@ jobs:
         with:
           payload: |
             {
-              "text": "E2E tests (${{ github.ref_name }} against ${{ env.TEST_AGAINST }}) failed: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+              "text": "E2E tests "${{ env.TEST_MODE }}" (${{ env.REF }} against ${{ env.TEST_AGAINST }}) failed with status "${{ job.status }}"\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
               "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "E2E tests (${{ github.ref_name }} against ${{ env.TEST_AGAINST }}) failed: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                    "text": "E2E tests "${{ env.TEST_MODE }}" (${{ env.REF }} against ${{ env.TEST_AGAINST }}) failed with status "${{ job.status }}"\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                   }
                 }
               ]
